services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=AzureDevOps!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./datadocker:/var/opt/mssql/data